#! /bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME"/statusblocks
CONFIG_FILE="$CONFIG_DIR"/statusblocks.conf

. "$CONFIG_FILE"

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

get_fifo_updates(){
    while read -r line ; do
        for signal in $PANEL_FIFO_SIGNALS; do
            pkill -RTMIN+$(expr "$signal") statusblocks
        done
    done
}

feed_fifo
get_fifo_updates < "$PANEL_FIFO" &

statusblocks "$CONFIG_DIR"/bar1 | panel_command &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N "$WM_WM_CLASS" -n "$WM_WM_NAME" | sort | head -n 1)" "$wid"

wait
