#! /bin/sh

. "$XDG_CONFIG_HOME"/statusblocks/panel_config

PANEL_FIFO="${PANEL_FIFO:-/tmp/panel-fifo}"

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

# trap 'trap - TERM; kill -9 "$(pidof statusblocks)"; kill 0' INT TERM QUIT EXIT
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

update_wm_block(){
    while read -r line ; do
        pkill -RTMIN+"${1:-1}" statusblocks
    done
}

bspc subscribe report > "$PANEL_FIFO" &
update_wm_block 1 < "$PANEL_FIFO" &

[ "$1" = "--debug" ] && statusblocks ||
    statusblocks | panel_command &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
